spring.application.name=restaurant-review
server.port=8080
logging.level.com.example.restaurantrating=DEBUG
springdoc-openapi.ui.path=/swagger-ui.html
springdoc-openapi.api-docs.path=/api-docs
spring.jpa.open-in-view=false
